spring.application.name=VMS-PERFORMANCE
spring.datasource.url=jdbc:postgresql://ep-little-math-a1ukftvp-pooler.ap-southeast-1.aws.neon.tech:5432/performancedb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_K8wgrhmG1YLv

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000