version: '3'

services:

  api-gateway:
    build: ./VMS-API-GATEWAY
    ports:
      - "8080:8080"

  auth:
    build: ./VMS-AUTH

  eureka:
    build: ./VMS-EUREKA-SERVER
    ports:
      - "8761:8761"

  orders:
    build: ./VMS-ORDERS

  payments:
    build: ./VMS-PAYMENTS

  performance:
    build: ./VMS-PERFORMANCE

  document:
    build: ./VMS-DOCUMENT

  dashboard:
    build: ./VMS-DASHBOARD