spring.application.name=VMS-ORDERS
spring.datasource.url=jdbc:postgresql://ep-little-math-a1ukftvp-pooler.ap-southeast-1.aws.neon.tech:5432/ordersdb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_K8wgrhmG1YLv

