server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:          
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ap-south-1
  bucket-name: vms-vendors-documents