spring.application.name=VMS-DOCUMENT
spring.datasource.url=jdbc:postgresql://ep-little-math-a1ukftvp-pooler.ap-southeast-1.aws.neon.tech:5432/documentdb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_K8wgrhmG1YLv

