server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: VMS-AUTH
        uri: lb://VMS-AUTH
        predicates:
          - Path=/api/auth/**,/api/organizations/**
      - id: VMS-VENDOR
        uri: lb://VMS-VENDOR
        predicates:
          - Path=/api/vendors/**,/api/partnerships/**
      - id: VMS-DOCUMENT
        uri: lb://VMS-DOCUMENT
        predicates:
          - Path=/api/documents/**
      - id: VMS-ORDERS
        uri: lb://VMS-ORDERS
        predicates:
          - Path=/api/orders/**,/api/invoices/**
      - id: VMS-PAYMENTS
        uri: lb://VMS-PAYMENTS
        predicates:
          - Path=/api/payments/**
      - id: VMS-PERFORMANCE
        uri: lb://VMS-PERFORMANCE
        predicates:
          - Path=/api/performance/**
      - id: VMS-DASHBOARD
        uri: lb://VMS-DASHBOARD
        predicates:
          - Path=/api/dashboard/**
